#!/bin/bash
WORK1=DP-2-1
WORK2=DP-1-2
LAPTOP=eDP-1
i3-msg workspace 1, move workspace to output $WORK1
i3-msg workspace 2, move workspace to output $WORK2
i3-msg workspace 5, move workspace to output $WORK1
i3-msg workspace 10, move workspace to output $LAPTOP

bash $HOME/.config/polybar/launch.sh mainbar-i3 $(xrandr | grep -w 'primary' | cut -f1 -d' ')
notify-send "Configured work"
